version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      dependencies:
        patterns: ['*']
        update-types: ['minor', 'patch']
      major-updates:
        patterns: ['*']
        update-types: ['major']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/docker'
    schedule:
      interval: 'daily'